# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e2f232838b9417d92426553c85dd9f0acfa3492453c49127e66c45eee223afee79d57f9a3b23aae32d826a77655da01eac5c366934286d52ef61f90ff2b7123e

test:
  secret_key_base: 3fd9898dd1aebe45d71ed5d658dbc3fc5b44875f289836de80370820588c55fe7b197279fd8964bf486d3691e739585079eda118e4a0188198fbf67bb0b3adbd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
